name: Pull Request
on:
  pull_request:
    types: [synchronize, opened, edited]
jobs:
  skip:
    name: Check Duplicate Actions
    runs-on: ubuntu-latest
    outputs:
      should-skip: ${{steps.skip-check.outputs.should_skip}}
    steps:
      - name: Skip Duplicate Actions (Pull Request)
        uses: fkirc/skip-duplicate-actions@f11521568414503656a5af807dc3018c012552c4 # tag=v5.2.0
        id: skip-check
  spellcheck:
    name: Spellcheck
    runs-on: ubuntu-latest
    needs: skip
    if: needs.skip.outputs.should-skip != 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3
      - name: Checking Spelling
        uses: crate-ci/typos@eff3fe8444c5b064cbfa24dac1fdb3fc9bb8c6d4 # tag=v1.12.14
        with:
          config: ${{github.workspace}}/.github/settings/typos.toml
  actions:
    name: Lint Action Workflows
    runs-on: ubuntu-latest
    needs: skip
    if: needs.skip.outputs.should-skip != 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3
      - name: Review Dog - actionlint
        uses: reviewdog/action-actionlint@7556c222a14ff4583c0f772caeb7f65bb3816dc1 # tag=v1
  golang:
    name: Lint Golang
    runs-on: ubuntu-latest
    needs: skip
    if: needs.skip.outputs.should-skip != 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3
      - name: Review Dog - golangci-lint
        uses: reviewdog/action-golangci-lint@53f8eabb87b40b1a2c63ec75b0d418bd0f4aa919 # tag=v2
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    needs: skip
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    if: needs.skip.outputs.should-skip != 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3
      - name: Setup Go
        uses: actions/setup-go@c4a742cab115ed795e34d4513e2cf7d472deb55f # tag=v3
        with:
          go-version: 1.17
      - name: Get Go Modules Cache Location
        run: echo "::set-output name=dir::$(go env GOMODCACHE)"
        id: go-modules-cache
      - name: Get Go Build Cache Location
        run: echo "::set-output name=dir::$(go env GOCACHE)"
        id: go-build-cache
      - name: Setup Go Modules Cache
        uses: actions/cache@1c73980b09e7aea7201f325a7aa3ad00beddcdda # tag=v3
        with:
          restore-keys: ${{ runner.os }}-go-modules-
          path: ${{ steps.go-modules-cache.outputs.dir }}
          key: ${{ runner.os }}-go-modules-${{ hashFiles('**/go.sum') }}
      - name: Setup Go Build Cache
        uses: actions/cache@1c73980b09e7aea7201f325a7aa3ad00beddcdda # tag=v3
        with:
          restore-keys: ${{ runner.os }}-go-build-
          path: ${{ steps.go-build-cache.outputs.dir }}
          key: ${{ runner.os}}-go-build-${{ hashFiles('**/go.mod', '**/go.sum') }}
      - name: Build Library
        run: go build
      - name: Analyze Library
        run: go vet
      - name: Run Tests
        run: >-
          go test -v .
          -coverprofile coverage.out
          -cover ${{github.workspace}}
      - name: Upload Code Coverage
        uses: codecov/codecov-action@d9f34f8cd5cb3b3eb79b3e4b5dae3a16df499a70 # tag=v3
        with:
          fail_ci_if_error: true
          directory: ${{ github.workspace }}
          files: coverage.out
