name: Pull Request
on:
  pull_request:
    types: [synchronize, opened, edited]
jobs:
  skip:
    name: Check Duplicate Actions
    runs-on: ubuntu-latest
    outputs:
      should-skip: ${{steps.skip-check.outputs.should_skip}}
    steps:
      - name: Skip Duplicate Actions (Pull Request)
        uses: fkirc/skip-duplicate-actions@f11521568414503656a5af807dc3018c012552c4 # tag=v5.2.0
        id: skip-check
  spellcheck:
    name: Spellcheck
    runs-on: ubuntu-latest
    needs: skip
    if: needs.skip.outputs.should-skip != 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
      - name: Checking Spelling
        uses: crate-ci/typos@2fc71b2e137baf80874f1c7272bae60dc036f8f4 # tag=v1.12.10
        with:
          config: ${{github.workspace}}/.github/settings/typos.toml
  actions:
    name: Lint Action Workflows
    runs-on: ubuntu-latest
    needs: skip
    if: needs.skip.outputs.should-skip != 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
      - name: Review Dog - actionlint
        uses: reviewdog/action-actionlint@c5d7b203340dfcb0f18fdf2ea44b0c10a1dee012 # tag=v1
  golang:
    name: Lint Golang
    runs-on: ubuntu-latest
    needs: skip
    if: needs.skip.outputs.should-skip != 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
      - name: Review Dog - golangci-lint
        uses: reviewdog/action-golangci-lint@53f8eabb87b40b1a2c63ec75b0d418bd0f4aa919 # tag=v2
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    needs: skip
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    if: needs.skip.outputs.should-skip != 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
      - name: Setup Go
        uses: actions/setup-go@268d8c0ca0432bb2cf416faae41297df9d262d7f # tag=v3
        with:
          go-version: 1.17
      - name: Get Go Modules Cache Location
        run: echo "::set-output name=dir::$(go env GOMODCACHE)"
        id: go-modules-cache
      - name: Get Go Build Cache Location
        run: echo "::set-output name=dir::$(go env GOCACHE)"
        id: go-build-cache
      - name: Setup Go Modules Cache
        uses: actions/cache@56461b9eb0f8438fd15c7a9968e3c9ebb18ceff1 # tag=v3
        with:
          restore-keys: ${{ runner.os }}-go-modules-
          path: ${{ steps.go-modules-cache.outputs.dir }}
          key: ${{ runner.os }}-go-modules-${{ hashFiles('**/go.sum') }}
      - name: Setup Go Build Cache
        uses: actions/cache@56461b9eb0f8438fd15c7a9968e3c9ebb18ceff1 # tag=v3
        with:
          restore-keys: ${{ runner.os }}-go-build-
          path: ${{ steps.go-build-cache.outputs.dir }}
          key: ${{ runner.os}}-go-build-${{ hashFiles('**/go.mod', '**/go.sum') }}
      - name: Build Library
        run: go build
      - name: Analyze Library
        run: go vet
      - name: Run Tests
        run: >-
          go test -v .
          -coverprofile coverage.out
          -cover ${{github.workspace}}
      - name: Upload Code Coverage
        uses: codecov/codecov-action@d9f34f8cd5cb3b3eb79b3e4b5dae3a16df499a70 # tag=v3
        with:
          fail_ci_if_error: true
          directory: ${{ github.workspace }}
          files: coverage.out
