name: Pull Request
on:
  pull_request:
    types: [synchronize, opened, edited]
jobs:
  skip:
    name: Check Duplicate Actions
    runs-on: ubuntu-latest
    outputs:
      should-skip: ${{steps.skip-check.outputs.should_skip}}
    steps:
      - name: Skip Duplicate Actions (Pull Request)
        uses: fkirc/skip-duplicate-actions@f11521568414503656a5af807dc3018c012552c4 # tag=v5.2.0
        id: skip-check
  spellcheck:
    name: Spellcheck
    runs-on: ubuntu-latest
    needs: skip
    if: needs.skip.outputs.should-skip != 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
      - name: Checking Spelling
        uses: crate-ci/typos@45a93446f27646f840207351d21cd815920d286f # tag=v1.12.8
        with:
          config: ${{github.workspace}}/.github/settings/typos.toml
  actions:
    name: Lint Action Workflows
    runs-on: ubuntu-latest
    needs: skip
    if: needs.skip.outputs.should-skip != 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
      - name: Review Dog - actionlint
        uses: reviewdog/action-actionlint@fe5c2db6029881e0b5634d7cb0d119b0c16b6922 # tag=v1
  golang:
    name: Lint Golang
    runs-on: ubuntu-latest
    needs: skip
    if: needs.skip.outputs.should-skip != 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
      - name: Review Dog - golangci-lint
        uses: reviewdog/action-golangci-lint@70498f2d1f75a55ee9a4d719e74e21ed68aebea3 # tag=v2
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    needs: skip
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    if: needs.skip.outputs.should-skip != 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
      - name: Setup Go
        uses: actions/setup-go@268d8c0ca0432bb2cf416faae41297df9d262d7f # tag=v3
        with:
          go-version: 1.17
      - name: Get Go Modules Cache Location
        run: echo "::set-output name=dir::$(go env GOMODCACHE)"
        id: go-modules-cache
      - name: Get Go Build Cache Location
        run: echo "::set-output name=dir::$(go env GOCACHE)"
        id: go-build-cache
      - name: Setup Go Modules Cache
        uses: actions/cache@ac8075791e805656e71b4ba23325ace9e3421120 # tag=v3
        with:
          restore-keys: ${{ runner.os }}-go-modules-
          path: ${{ steps.go-modules-cache.outputs.dir }}
          key: ${{ runner.os }}-go-modules-${{ hashFiles('**/go.sum') }}
      - name: Setup Go Build Cache
        uses: actions/cache@ac8075791e805656e71b4ba23325ace9e3421120 # tag=v3
        with:
          restore-keys: ${{ runner.os }}-go-build-
          path: ${{ steps.go-build-cache.outputs.dir }}
          key: ${{ runner.os}}-go-build-${{ hashFiles('**/go.mod', '**/go.sum') }}
      - name: Build Library
        run: go build
      - name: Analyze Library
        run: go vet
      - name: Run Tests
        run: >-
          go test -v .
          -coverprofile coverage.out
          -cover ${{github.workspace}}
      - name: Upload Code Coverage
        uses: codecov/codecov-action@d9f34f8cd5cb3b3eb79b3e4b5dae3a16df499a70 # tag=v3
        with:
          fail_ci_if_error: true
          directory: ${{ github.workspace }}
          files: coverage.out
