name: Pull Request
on:
  pull_request:
    types: [synchronize, opened, edited]
jobs:
  skip:
    name: Check Duplicate Actions
    runs-on: ubuntu-latest
    outputs:
      should-skip: ${{steps.skip-check.outputs.should_skip}}
    steps:
      - name: Skip Duplicate Actions (Pull Request)
        uses: fkirc/skip-duplicate-actions@12aca0a884f6137d619d6a8a09fcc3406ced5281 # v5.3.0
        id: skip-check
  spellcheck:
    name: Spellcheck
    runs-on: ubuntu-latest
    needs: skip
    if: needs.skip.outputs.should-skip != 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
      - name: Checking Spelling
        uses: crate-ci/typos@6efbdc33f4385365c41520d44be74034513c8fcf # v1.13.6
        with:
          config: ${{github.workspace}}/.github/settings/typos.toml
  actions:
    name: Lint Action Workflows
    runs-on: ubuntu-latest
    needs: skip
    if: needs.skip.outputs.should-skip != 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
      - name: Review Dog - actionlint
        uses: reviewdog/action-actionlint@326cc761d95c903f29a111a44888be707f912684 # v1
  golang:
    name: Lint Golang
    runs-on: ubuntu-latest
    needs: skip
    if: needs.skip.outputs.should-skip != 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
      - name: Review Dog - golangci-lint
        uses: reviewdog/action-golangci-lint@53f8eabb87b40b1a2c63ec75b0d418bd0f4aa919 # tag=v2
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    needs: skip
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    if: needs.skip.outputs.should-skip != 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
      - name: Setup Go
        uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # v3
        with:
          go-version: 1.17
      - name: Get Go Modules Cache Location
        run: echo "::set-output name=dir::$(go env GOMODCACHE)"
        id: go-modules-cache
      - name: Get Go Build Cache Location
        run: echo "::set-output name=dir::$(go env GOCACHE)"
        id: go-build-cache
      - name: Setup Go Modules Cache
        uses: actions/cache@4723a57e26efda3a62cbde1812113b730952852d # v3
        with:
          restore-keys: ${{ runner.os }}-go-modules-
          path: ${{ steps.go-modules-cache.outputs.dir }}
          key: ${{ runner.os }}-go-modules-${{ hashFiles('**/go.sum') }}
      - name: Setup Go Build Cache
        uses: actions/cache@4723a57e26efda3a62cbde1812113b730952852d # v3
        with:
          restore-keys: ${{ runner.os }}-go-build-
          path: ${{ steps.go-build-cache.outputs.dir }}
          key: ${{ runner.os}}-go-build-${{ hashFiles('**/go.mod', '**/go.sum') }}
      - name: Build Library
        run: go build
      - name: Analyze Library
        run: go vet
      - name: Run Tests
        run: >-
          go test -v .
          -coverprofile coverage.out
          -cover ${{github.workspace}}
      - name: Upload Code Coverage
        uses: codecov/codecov-action@d9f34f8cd5cb3b3eb79b3e4b5dae3a16df499a70 # tag=v3
        with:
          fail_ci_if_error: true
          directory: ${{ github.workspace }}
          files: coverage.out
